# build machine - the computer that will compile the program
# host machine - the machine on which the compiled binary will run
[binaries]
c = 'arm-none-eabi-gcc'
cpp = 'arm-none-eabi-g++'
ar = 'arm-none-eabi-ar'
ld = 'arm-none-eabi-g++'
objcopy = 'arm-none-eabi-objcopy'
strip = 'arm-none-eabi-strip'